In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#import dataset
data=pd.read_csv('Dataset.csv')

In [6]:
data.tail(10)

Day      Date  CodedDay  Zone  Weather  Temperature  Traffic
1429  Friday  10-06-18         5   135       18           25        4
1430  Friday  10-06-18         5   136       31            8        2
1431  Friday  10-06-18         5   137       13           11        4
1432  Friday  10-06-18         5   138       34           15        1
1433  Friday  10-06-18         5   139        5           43        4
1434  Friday  10-06-18         5   140       47           38        1
1435  Friday  10-06-18         5   141       15            8        4
1436  Friday  10-06-18         5   142       26           38        1
1437  Friday  10-06-18         5   143       16           34        3
1438  Friday  10-06-18         5   144       16           17        1

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          1439 non-null   object
 1   Date         1439 non-null   object
 2   CodedDay     1439 non-null   int64 
 3   Zone         1439 non-null   int64 
 4   Weather      1439 non-null   int64 
 5   Temperature  1439 non-null   int64 
 6   Traffic      1439 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 78.8+ KB


In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()

In [11]:
data['Date']=le.fit_transform(data['Date'])
data

Day  Date  CodedDay  Zone  Weather  Temperature  Traffic
0     Wednesday     0         3     2       35           17        2
1     Wednesday     0         3     3       36           16        3
2     Wednesday     0         3     4       27           25        5
3     Wednesday     0         3     5       23           23        3
4     Wednesday     0         3     6       18           42        2
...         ...   ...       ...   ...      ...          ...      ...
1434     Friday     9         5   140       47           38        1
1435     Friday     9         5   141       15            8        4
1436     Friday     9         5   142       26           38        1
1437     Friday     9         5   143       16           34        3
1438     Friday     9         5   144       16           17        1

[1439 rows x 7 columns]

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Day          1439 non-null   object
 1   Date         1439 non-null   int32 
 2   CodedDay     1439 non-null   int64 
 3   Zone         1439 non-null   int64 
 4   Weather      1439 non-null   int64 
 5   Temperature  1439 non-null   int64 
 6   Traffic      1439 non-null   int64 
dtypes: int32(1), int64(5), object(1)
memory usage: 73.2+ KB


In [13]:
x=data.iloc[:,2:6].values
y=data.iloc[:,6:7].values

In [14]:
x

array([[  3,   2,  35,  17],
       [  3,   3,  36,  16],
       [  3,   4,  27,  25],
       ...,
       [  5, 142,  26,  38],
       [  5, 143,  16,  34],
       [  5, 144,  16,  17]], dtype=int64)

In [15]:
x.shape

(1439, 4)

In [16]:
y

array([[2],
       [3],
       [5],
       ...,
       [1],
       [3],
       [1]], dtype=int64)

In [17]:
y.shape

(1439, 1)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [21]:
x_train.shape,y_train.shape

((1151, 4), (1151, 1))

In [22]:
x_test.shape,y_test.shape

((288, 4), (288, 1))

In [23]:
#feature Scaling

from sklearn.preprocessing import StandardScaler

In [24]:
sc=StandardScaler()

In [25]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [26]:
x_train

array([[ 1.14531281e+00,  2.11762730e-01,  1.62298702e+00,
        -1.49262367e+00],
       [ 1.14531281e+00, -5.11784378e-01, -1.51679228e-01,
        -6.41479902e-02],
       [-5.70420435e-01, -7.04730273e-01,  1.54904259e+00,
        -1.53427720e-01],
       ...,
       [ 1.49064574e-03, -1.74129061e-01, -8.17179071e-01,
        -5.10546640e-01],
       [ 1.14531281e+00,  1.34531987e+00, -1.51679228e-01,
        -5.99826371e-01],
       [ 1.71722389e+00,  8.87073364e-01,  1.25326488e+00,
         1.36432769e+00]])

In [29]:
#random foresrt
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=300,
                                random_state=0)


In [30]:
regressor.fit(x_train,y_train)

C:\Users\Software\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(n_estimators=300, random_state=0)

In [31]:
y_pred=regressor.predict(x_test)

In [32]:
y_pred

array([3.49666667, 3.77666667, 2.59333333, 3.78333333, 2.30333333,
       2.54333333, 3.01      , 2.62333333, 3.61666667, 2.25333333,
       3.16      , 3.01666667, 2.71333333, 2.76666667, 3.79      ,
       2.29333333, 2.41666667, 3.06333333, 3.28333333, 2.98      ,
       3.47666667, 2.5       , 3.03333333, 2.4       , 2.63      ,
       2.94      , 2.20666667, 3.36333333, 2.53333333, 2.79666667,
       2.69666667, 3.2       , 3.27      , 2.18      , 3.07      ,
       2.13666667, 3.36      , 4.08333333, 2.99      , 3.11666667,
       2.79      , 3.82      , 2.72      , 3.91333333, 3.34      ,
       3.58333333, 3.17      , 2.55666667, 2.41      , 3.57      ,
       4.12333333, 3.51      , 3.86      , 2.78333333, 3.16333333,
       3.04      , 3.14      , 2.64333333, 2.76333333, 2.45666667,
       3.27333333, 2.67333333, 2.97333333, 1.59666667, 3.05      ,
       3.74333333, 3.04666667, 3.90666667, 2.55666667, 3.29333333,
       2.85      , 3.33333333, 3.15333333, 3.18333333, 2.79   

In [33]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)
y_pred

array([3., 3., 2., 3., 2., 2., 3., 2., 3., 2., 3., 3., 2., 2., 3., 2., 2.,
       3., 3., 2., 3., 2., 3., 2., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.,
       3., 2., 3., 4., 2., 3., 2., 3., 2., 3., 3., 3., 3., 2., 2., 3., 4.,
       3., 3., 2., 3., 3., 3., 2., 2., 2., 3., 2., 2., 1., 3., 3., 3., 3.,
       2., 3., 2., 3., 3., 3., 2., 3., 3., 2., 2., 3., 2., 2., 3., 2., 3.,
       3., 3., 3., 3., 2., 3., 2., 2., 3., 2., 3., 2., 3., 3., 3., 2., 2.,
       2., 2., 3., 2., 3., 2., 2., 3., 2., 3., 2., 2., 3., 3., 3., 2., 3.,
       2., 3., 3., 2., 2., 3., 3., 2., 3., 4., 1., 2., 3., 3., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 2., 3., 3., 2., 3., 3., 3., 2., 2., 2., 3.,
       2., 3., 2., 3., 2., 3., 3., 2., 2., 3., 2., 2., 2., 3., 2., 2., 3.,
       3., 3., 2., 3., 3., 2., 2., 2., 2., 2., 2., 3., 3., 3., 2., 3., 2.,
       2., 2., 2., 1., 2., 3., 2., 3., 2., 2., 2., 2., 4., 3., 3., 2., 3.,
       3., 3., 3., 3., 3., 3., 3., 1., 3., 3., 2., 3., 3., 3., 2., 3., 3.,
       3., 2., 3., 3., 2.

In [34]:
df=(y_pred-y_test)/y_test
df=round(df.mean()*100,2)
print("Error=",df,"%")

Error= 13.42 %


In [35]:
a=100-df
print("Accuracy=",a,"%")

Accuracy= 86.58 %


In [36]:
#SVM
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)

y_pred

C:\Users\Software\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([2.48568787, 3.83075078, 3.2936518 , 3.1673047 , 2.92523973,
       2.31572795, 2.36996983, 2.19128844, 3.66497598, 2.56215864,
       3.09770455, 3.37561416, 2.86955855, 2.70819912, 2.51284476,
       2.60066084, 2.4309671 , 2.37138504, 3.18637153, 2.83358309,
       3.60021418, 2.48652871, 3.03685709, 2.39762196, 2.497879  ,
       3.11026378, 2.99161215, 3.69680818, 3.09097039, 2.62917555,
       2.84167464, 3.26385761, 2.957667  , 3.15259094, 3.1129895 ,
       2.65382723, 2.64573348, 4.17701652, 3.1214746 , 2.59892333,
       2.54551056, 3.67757031, 2.76428867, 3.82274378, 3.06953225,
       2.93527699, 2.77584091, 2.67888664, 2.3393692 , 3.94660356,
       2.98060755, 3.72745618, 4.06289067, 3.18461613, 2.79760641,
       3.16032156, 2.40107766, 3.05992469, 2.50326614, 3.14948545,
       2.0258538 , 2.39031143, 2.5313014 , 2.06376862, 3.25822173,
       3.8331732 , 2.91792523, 4.16926464, 2.99944268, 2.72893788,
       2.7935679 , 3.48603414, 3.09625424, 3.2274822 , 3.18776

In [37]:
if(y_pred.all()<2.5):
    y_pred=np.round(y_pred-0.5)
else:
    y_pred=np.round(y_pred+0.5)
y_pred

array([2., 3., 3., 3., 2., 2., 2., 2., 3., 2., 3., 3., 2., 2., 2., 2., 2.,
       2., 3., 2., 3., 2., 3., 2., 2., 3., 2., 3., 3., 2., 2., 3., 2., 3.,
       3., 2., 2., 4., 3., 2., 2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 2.,
       3., 4., 3., 2., 3., 2., 3., 2., 3., 2., 2., 2., 2., 3., 3., 2., 4.,
       2., 2., 2., 3., 3., 3., 3., 3., 3., 2., 2., 3., 1., 2., 3., 3., 2.,
       2., 2., 3., 3., 2., 3., 2., 3., 3., 2., 2., 2., 3., 3., 3., 2., 3.,
       2., 3., 2., 3., 3., 2., 3., 2., 3., 3., 2., 2., 3., 3., 2., 3., 2.,
       2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 2., 2., 3., 3., 1., 4., 3.,
       3., 3., 3., 3., 2., 3., 2., 3., 3., 3., 2., 2., 2., 2., 2., 2., 3.,
       3., 2., 2., 2., 2., 3., 2., 2., 2., 2., 2., 3., 3., 2., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 1., 2., 3., 2., 2., 3., 2., 3., 3., 2., 3.,
       2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 3., 2., 3., 1., 2., 2., 3.,
       2., 3., 2., 3., 2., 3., 3., 1., 3., 2., 3., 3., 3., 3., 3., 3., 3.,
       3., 2., 2., 2., 2.

In [38]:
df=(y_pred-y_test)/y_test
df=round(df.mean()*100,2)
print("Error=",df,"%")

Error= 12.16 %


In [39]:
a=100-df
print("Accuracy=",a,"%")

Accuracy= 87.84 %
